[package]
name = "minigrep_nanami_20210502"
version = "0.1.0"
authors = ["nanami"]
edition = "2018"
licence="MIT"
description = "practice Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
